-- MySQL Script generated by MySQL Workbench
-- Thu Nov  3 23:30:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Examen-2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Examen-2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Examen-2` DEFAULT CHARACTER SET utf8 ;
USE `Examen-2` ;

-- -----------------------------------------------------
-- Table `Examen-2`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen-2`.`Usuario` (
  `Codigo_Usuario` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen-2`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen-2`.`Cliente` (
  `Codigo_Cliente` VARCHAR(15) NOT NULL,
  `Nombre_cliente` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Descri_Solicitud` VARCHAR(100) NULL,
  PRIMARY KEY (`Codigo_Cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen-2`.`Tipos_Soporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen-2`.`Tipos_Soporte` (
  `Codigo_Sop` VARCHAR(45) NOT NULL,
  `Precio` DECIMAL NULL,
  PRIMARY KEY (`Codigo_Sop`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen-2`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen-2`.`Tickets` (
  `Id_Tickets` INT NOT NULL AUTO_INCREMENT,
  `Codigo_Cliente` VARCHAR(45) NULL,
  `T_Soporte` VARCHAR(45) NULL,
  `Desc_Soporte` VARCHAR(100) NOT NULL,
  `Respuesta` VARCHAR(120) NOT NULL,
  `Precio` INT NOT NULL,
  `Impuesto` INT NULL,
  `Descu` INT NULL,
  `Total` INT NULL,
  `Codigo_Usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_Tickets`),
  INDEX `FK_Ticket_Cliente_idx` (`Codigo_Cliente` ASC) VISIBLE,
  INDEX `FK_Ticket_Soporte_idx` (`T_Soporte` ASC) VISIBLE,
  INDEX `FK_Ticket_Usuario_idx` (`Codigo_Usuario` ASC) VISIBLE,
  CONSTRAINT `FK_Ticket_Cliente`
    FOREIGN KEY (`Codigo_Cliente`)
    REFERENCES `Examen-2`.`Cliente` (`Codigo_Cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Ticket_Soporte`
    FOREIGN KEY (`T_Soporte`)
    REFERENCES `Examen-2`.`Tipos_Soporte` (`Codigo_Sop`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Ticket_Usuario`
    FOREIGN KEY (`Codigo_Usuario`)
    REFERENCES `Examen-2`.`Usuario` (`Codigo_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
